name: mucy
description: Creates strong mental habits in youth to handle the challenges and opportunities that life creates.

publish_to: 'none'

version: 0.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.14.1
  auto_route: ^0.6.9
  get_it: ^5.0.1
  injectable: ^1.0.5
  stacked: ^1.7.6
  stacked_services: ^0.5.4+4
  stacked_hooks: ^0.1.3+1
  google_fonts: ^1.1.1
  flutter_svg: ^0.19.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  animated_widgets: ^1.0.6
  simple_animations: ^2.4.2
  auto_animated: ^2.1.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  build_runner: ^1.10.4
  hive_generator: ^0.8.2
  auto_route_generator: ^0.6.10
  injectable_generator: ^1.0.6
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/appicon-low-res.png"

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: VAG Rounded STD
     fonts:
      - asset: assets/fonts/VAG-Rounded-Std-Black.ttf
      - asset: assets/fonts/VAG-Rounded-Std-Bold.ttf
        weight: 700
      - asset: assets/fonts/VAG-Rounded-Std-Light.ttf
      - asset: assets/fonts/VAG-Rounded-Std-Thin.ttf